/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 20 00:00:16 GMT 2026
 */

package com.example.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.calculator.BuiltinFunctionCatalog;
import com.example.calculator.FunctionDefinition;
import java.util.Map;
import java.util.Random;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BuiltinFunctionCatalog_ESTest extends BuiltinFunctionCatalog_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Map<String, FunctionDefinition> map0 = BuiltinFunctionCatalog.create((Random) null);
      assertEquals(50, map0.size());
  }
}
