/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Feb 19 23:56:25 GMT 2026
 */

package com.example.calculator;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class CalculatorApp_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.example.calculator.CalculatorApp"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
    org.evosuite.runtime.util.SystemInUtil.getInstance().initForTestCase(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/evosuite"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CalculatorApp_ESTest_scaffolding.class.getClassLoader() ,
      "com.example.calculator.CalculatorApp",
      "com.example.calculator.CalculatorEngine",
      "com.example.calculator.ExpressionParser$TokenType",
      "com.example.calculator.CommandResult",
      "com.example.calculator.ExpressionParser$SymbolResolver",
      "com.example.calculator.ExpressionParser$FunctionResolver",
      "com.example.calculator.CalculatorException",
      "com.example.calculator.BuiltinFunctionCatalog",
      "com.example.calculator.FunctionDefinition$FunctionImplementation",
      "com.example.calculator.CalculatorMath",
      "com.example.calculator.ExpressionParser$Token",
      "com.example.calculator.FunctionDefinition",
      "com.example.calculator.StatementSplitter",
      "com.example.calculator.CalculatorState",
      "com.example.calculator.CalculatorCommandProcessor",
      "com.example.calculator.ExpressionParser"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CalculatorApp_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.example.calculator.CalculatorApp",
      "com.example.calculator.CalculatorCommandProcessor",
      "com.example.calculator.CalculatorEngine",
      "com.example.calculator.CalculatorState",
      "com.example.calculator.BuiltinFunctionCatalog",
      "com.example.calculator.FunctionDefinition",
      "com.example.calculator.StatementSplitter",
      "com.example.calculator.CalculatorException",
      "com.example.calculator.ExpressionParser",
      "com.example.calculator.ExpressionParser$TokenType",
      "com.example.calculator.ExpressionParser$Token",
      "com.example.calculator.CommandResult",
      "com.example.calculator.NumberFormatUtil",
      "com.example.calculator.HistoryEntry",
      "com.example.calculator.CalculatorMath"
    );
  }
}
