/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 20 00:02:05 GMT 2026
 */

package com.example.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.calculator.CalculatorMath;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CalculatorMath_ESTest extends CalculatorMath_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      boolean boolean0 = CalculatorMath.isPrime(1681.0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      boolean boolean0 = CalculatorMath.isPrime(1250.0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      boolean boolean0 = CalculatorMath.isPrime(2.0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      boolean boolean0 = CalculatorMath.isPrime(1.0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      double double0 = CalculatorMath.fibonacci(2.0);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        CalculatorMath.fibonacci(1681.0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // fib(n): n too large (max 92).
         //
         verifyException("com.example.calculator.CalculatorMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      double double0 = CalculatorMath.fibonacci(1.0E-12);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      double double0 = CalculatorMath.combination(2.0, 1.0);
      assertEquals(2.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        CalculatorMath.combination(1681.0, 543.0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // comb(n, k) overflowed.
         //
         verifyException("com.example.calculator.CalculatorMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        CalculatorMath.permutation(1681.0, 1681.0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // perm(n, k) overflowed.
         //
         verifyException("com.example.calculator.CalculatorMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        CalculatorMath.permutation(0L, 1.0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // perm(n, k) requires k <= n.
         //
         verifyException("com.example.calculator.CalculatorMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      double double0 = CalculatorMath.permutation(1.0, 1.0);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      Double double0 = new Double(1480.196);
      linkedList0.add(double0);
      double double1 = CalculatorMath.medianOf(linkedList0);
      assertEquals(1480.196, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      // Undeclared exception!
      try { 
        CalculatorMath.medianOf(linkedList0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("com.example.calculator.CalculatorMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      Double double0 = new Double(1020.163093012);
      linkedList0.add(double0);
      double double1 = CalculatorMath.varianceOf(linkedList0);
      assertEquals(0.0, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      Double double0 = new Double(392.15);
      linkedList0.add(double0);
      double double1 = CalculatorMath.productOf(linkedList0);
      assertEquals(392.15, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      Double double0 = new Double(2.0);
      linkedList0.add(double0);
      Double double1 = new Double(0.0);
      linkedList0.add(double1);
      double double2 = CalculatorMath.lcmOf(linkedList0);
      assertEquals(0.0, double2, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Double double0 = new Double(0.0);
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      linkedList0.add(double0);
      linkedList0.add(double0);
      double double1 = CalculatorMath.lcmOf(linkedList0);
      assertEquals(0.0, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      // Undeclared exception!
      try { 
        CalculatorMath.lcmOf(linkedList0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // lcm requires at least 2 arguments.
         //
         verifyException("com.example.calculator.CalculatorMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      // Undeclared exception!
      try { 
        CalculatorMath.gcdOf(linkedList0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // gcd requires at least 2 arguments.
         //
         verifyException("com.example.calculator.CalculatorMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      Double double0 = new Double(0.0);
      linkedList0.add(double0);
      linkedList0.add(double0);
      double double1 = CalculatorMath.gcdOf(linkedList0);
      assertEquals(0.0, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      Double double0 = new Double(1.0);
      linkedList0.add(double0);
      linkedList0.add(double0);
      double double1 = CalculatorMath.lcmOf(linkedList0);
      assertEquals(1.0, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      // Undeclared exception!
      try { 
        CalculatorMath.clamp((-4076.6), 0.11081854169799499, (-4076.6));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // clamp(min, max): min cannot be greater than max.
         //
         verifyException("com.example.calculator.CalculatorMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      double double0 = CalculatorMath.clamp(1656.6226150719574, 1656.6226150719574, 1656.6226150719574);
      assertEquals(1656.6226150719574, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      boolean boolean0 = CalculatorMath.toBoolean(1681.0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      boolean boolean0 = CalculatorMath.toBoolean(0.0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      // Undeclared exception!
      try { 
        CalculatorMath.factorial(1681.0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Factorial input too large (max 170).
         //
         verifyException("com.example.calculator.CalculatorMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      double double0 = CalculatorMath.factorial(2.0);
      assertEquals(2.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      // Undeclared exception!
      try { 
        CalculatorMath.permutation((-1.0), (-1.0));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // perm n must be non-negative.
         //
         verifyException("com.example.calculator.CalculatorMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      // Undeclared exception!
      try { 
        CalculatorMath.combination(1.0, 2.0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // comb(n, k) requires k <= n.
         //
         verifyException("com.example.calculator.CalculatorMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      // Undeclared exception!
      try { 
        CalculatorMath.factorial((-1.1610619607159856));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Factorial input must be an integer.
         //
         verifyException("com.example.calculator.CalculatorMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      // Undeclared exception!
      try { 
        CalculatorMath.requireInteger(Double.NaN, "S4)B>G]");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // S4)B>G] must be finite.
         //
         verifyException("com.example.calculator.CalculatorMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      boolean boolean0 = CalculatorMath.isPrime(613.0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      // Undeclared exception!
      try { 
        CalculatorMath.standardDeviationOf((List<Double>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.calculator.CalculatorMath", e);
      }
  }
}
