/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 19 23:58:46 GMT 2026
 */

package com.example.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.calculator.CalculatorException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CalculatorException_ESTest extends CalculatorException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable((String) null);
      CalculatorException calculatorException0 = new CalculatorException((String) null, mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CalculatorException calculatorException0 = new CalculatorException("");
  }
}
