/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 20 00:03:46 GMT 2026
 */

package com.example.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.calculator.CalculatorState;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CalculatorState_ESTest extends CalculatorState_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      Double double0 = new Double(2708.8484);
      hashMap0.put("", double0);
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      boolean boolean0 = calculatorState0.hasConstant("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      boolean boolean0 = calculatorState0.hasConstant("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      boolean boolean0 = calculatorState0.removeVariable("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      calculatorState0.putVariable("", 1.0);
      boolean boolean0 = calculatorState0.hasVariable("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      boolean boolean0 = calculatorState0.hasVariable("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      Double double0 = new Double(604.5349330317624);
      hashMap0.put("", double0);
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      boolean boolean0 = calculatorState0.isConstant("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      boolean boolean0 = calculatorState0.isConstant("h");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      double double0 = calculatorState0.getAns();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      // Undeclared exception!
      try { 
        calculatorState0.getVariable("knh2zp1v+BtYFRx");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.calculator.CalculatorState", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      calculatorState0.putVariable("", 0.0);
      boolean boolean0 = calculatorState0.removeVariable("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      calculatorState0.clearVariables();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      Map<String, Double> map0 = calculatorState0.getVariablesSnapshot();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      calculatorState0.setAns((-1.0));
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      calculatorState0.setMemory((-482.0));
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      calculatorState0.reset();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      // Undeclared exception!
      try { 
        calculatorState0.resolveConstant("t;*uLtI");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.calculator.CalculatorState", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      Map<String, Double> map0 = calculatorState0.getConstantsSnapshot();
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HashMap<String, Double> hashMap0 = new HashMap<String, Double>();
      CalculatorState calculatorState0 = new CalculatorState(hashMap0);
      double double0 = calculatorState0.getMemory();
      assertEquals(0.0, double0, 0.01);
  }
}
