/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 19 23:58:11 GMT 2026
 */

package com.example.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.calculator.CalculatorEngine;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CalculatorEngine_ESTest extends CalculatorEngine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      // Undeclared exception!
      try { 
        calculatorEngine0.evaluateAll("cOs()");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // cOs requires at least 1 argument(s).
         //
         verifyException("com.example.calculator.CalculatorEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      // Undeclared exception!
      try { 
        calculatorEngine0.evaluateAll("cs()");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unknown function: cs
         //
         verifyException("com.example.calculator.CalculatorEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      // Undeclared exception!
      try { 
        calculatorEngine0.evaluate("expression");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unknown symbol: expression
         //
         verifyException("com.example.calculator.CalculatorEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      List<Double> list0 = calculatorEngine0.evaluateAll("e");
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      List<Double> list0 = calculatorEngine0.evaluateAll("memory");
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      List<Double> list0 = calculatorEngine0.evaluateAll("ans");
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      // Undeclared exception!
      try { 
        calculatorEngine0.deleteVariable("tau");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Cannot delete constant: tau
         //
         verifyException("com.example.calculator.CalculatorEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      boolean boolean0 = calculatorEngine0.deleteVariable("cOs(4)");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      Map<String, String> map0 = calculatorEngine0.getFunctionsHelp();
      assertEquals(50, map0.size());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      // Undeclared exception!
      try { 
        calculatorEngine0.evaluateAll(";");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Input is empty.
         //
         verifyException("com.example.calculator.CalculatorEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      // Undeclared exception!
      try { 
        calculatorEngine0.evaluateAll((String) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Input is empty.
         //
         verifyException("com.example.calculator.CalculatorEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      Map<String, Double> map0 = calculatorEngine0.getVariablesSnapshot();
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      calculatorEngine0.reset();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      calculatorEngine0.memoryStore(1778.8384057721519);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      // Undeclared exception!
      try { 
        calculatorEngine0.memoryAdd(Double.NEGATIVE_INFINITY);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Memory value is not finite.
         //
         verifyException("com.example.calculator.CalculatorEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      double double0 = calculatorEngine0.getAns();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      Map<String, Double> map0 = calculatorEngine0.getConstantsSnapshot();
      assertEquals(4, map0.size());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      calculatorEngine0.setRandomSeed(669L);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      double double0 = calculatorEngine0.evaluate("mem");
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      calculatorEngine0.memoryClear();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      List<Double> list0 = calculatorEngine0.evaluateAll("cOs(4)");
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      calculatorEngine0.memorySubtract((-902.7365));
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      double double0 = calculatorEngine0.memoryRecall();
      assertEquals(0.0, double0, 0.01);
  }
}
