/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 20 00:05:40 GMT 2026
 */

package com.example.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.calculator.CalculatorCommandProcessor;
import com.example.calculator.CalculatorEngine;
import com.example.calculator.CommandResult;
import com.example.calculator.HistoryEntry;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CalculatorCommandProcessor_ESTest extends CalculatorCommandProcessor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      CommandResult commandResult0 = calculatorCommandProcessor0.process(":quit");
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      CommandResult commandResult0 = calculatorCommandProcessor0.process(":exit");
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      CommandResult commandResult0 = calculatorCommandProcessor0.process("quit");
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      CommandResult commandResult0 = calculatorCommandProcessor0.process("M-");
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process("  M- [expr]  Subtract expression or ans from memory");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unexpected character '[' at position 0
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process("M+");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.calculator.CalculatorCommandProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process("  M+ [expr]  Add expression or ans to memory");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unexpected character '[' at position 0
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process("MS");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.calculator.CalculatorCommandProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process("  MS [expr]  Store expression or ans in memory");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unexpected character '[' at position 0
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      CommandResult commandResult0 = calculatorCommandProcessor0.process("  MC        Cler memory");
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process(":seed requires an integer value.");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Invalid seed value: requires an integer value.
         //
         verifyException("com.example.calculator.CalculatorCommandProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process(":del");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // :del requires a variable name.
         //
         verifyException("com.example.calculator.CalculatorCommandProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process(":m- [expr]  subtract expression or ans from memory");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unknown command: :m- (use :help)
         //
         verifyException("com.example.calculator.CalculatorCommandProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process(":reset");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.calculator.CalculatorCommandProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      CommandResult commandResult0 = calculatorCommandProcessor0.process(":funcs");
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process(":const");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.calculator.CalculatorCommandProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      CommandResult commandResult0 = calculatorCommandProcessor0.process(":clear");
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      CommandResult commandResult0 = calculatorCommandProcessor0.process(":functions");
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      CommandResult commandResult0 = calculatorCommandProcessor0.process(":Constants");
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      CommandResult commandResult0 = calculatorCommandProcessor0.process(":vars");
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process(":seed");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // :seed requires an integer value.
         //
         verifyException("com.example.calculator.CalculatorCommandProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process(":ans");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.calculator.CalculatorCommandProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      CommandResult commandResult0 = calculatorCommandProcessor0.process(":history");
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process(":memory");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.calculator.CalculatorCommandProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      CommandResult commandResult0 = calculatorCommandProcessor0.process(":del requires a variable name.");
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process("!");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // History recall requires an index. Example: !3
         //
         verifyException("com.example.calculator.CalculatorCommandProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      CommandResult commandResult0 = calculatorCommandProcessor0.process("mr         recall memory");
      calculatorCommandProcessor0.process("mr         recall memory");
      CommandResult commandResult1 = calculatorCommandProcessor0.process("!2");
      assertNotSame(commandResult1, commandResult0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      // Undeclared exception!
      try { 
        calculatorCommandProcessor0.process("!2");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // History index not found: 2
         //
         verifyException("com.example.calculator.CalculatorCommandProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      CommandResult commandResult0 = calculatorCommandProcessor0.process("exit");
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      CommandResult commandResult0 = calculatorCommandProcessor0.process("");
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      CommandResult commandResult0 = calculatorCommandProcessor0.process((String) null);
      assertNotNull(commandResult0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      CalculatorEngine calculatorEngine0 = new CalculatorEngine();
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor(calculatorEngine0);
      CommandResult commandResult0 = calculatorCommandProcessor0.process("memory");
      CommandResult commandResult1 = calculatorCommandProcessor0.process(":history");
      assertNotSame(commandResult1, commandResult0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      List<HistoryEntry> list0 = calculatorCommandProcessor0.historySnapshot();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      CalculatorCommandProcessor calculatorCommandProcessor0 = new CalculatorCommandProcessor((CalculatorEngine) null);
      CommandResult commandResult0 = calculatorCommandProcessor0.process(":help");
      assertNotNull(commandResult0);
  }
}
