/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 19 23:58:18 GMT 2026
 */

package com.example.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.calculator.CommandResult;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommandResult_ESTest extends CommandResult_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CommandResult commandResult0 = CommandResult.empty();
      boolean boolean0 = commandResult0.exitRequested();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CommandResult commandResult0 = CommandResult.exit();
      List<String> list0 = commandResult0.outputLines();
      CommandResult commandResult1 = CommandResult.ofLines(list0);
      assertFalse(commandResult1.equals((Object)commandResult0));
  }
}
