/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 20 00:07:35 GMT 2026
 */

package com.example.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.calculator.ExpressionParser;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ExpressionParser_ESTest extends ExpressionParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ExpressionParser expressionParser0 = null;
      try {
        expressionParser0 = new ExpressionParser(",3e2\"bpSW2n[", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unexpected character '\"' at position 4
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("||", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("&&", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser(">=", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("X)mGmp<=w", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("!=", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("==", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("7>", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ExpressionParser expressionParser0 = null;
      try {
        expressionParser0 = new ExpressionParser("Bs+K!w0_2_ ~", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unexpected character '' at position 8
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ExpressionParser expressionParser0 = null;
      try {
        expressionParser0 = new ExpressionParser("_#D8GM~CXP#-]fY2l", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unexpected character '#' at position 1
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ExpressionParser expressionParser0 = null;
      try {
        expressionParser0 = new ExpressionParser("1E-C$K", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Invalid exponent near position 1
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ExpressionParser expressionParser0 = null;
      try {
        expressionParser0 = new ExpressionParser("3e", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Invalid exponent near position 1
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ExpressionParser expressionParser0 = null;
      try {
        expressionParser0 = new ExpressionParser("1.C$K", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unexpected character '$' at position 3
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ExpressionParser expressionParser0 = null;
      try {
        expressionParser0 = new ExpressionParser("o..", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Invalid number near position 1
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ExpressionParser expressionParser0 = null;
      try {
        expressionParser0 = new ExpressionParser("Unexpected trailing input.", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Invalid number near position 25
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("(n", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
      // Undeclared exception!
      try { 
        expressionParser0.parse();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("rR(8uHI", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
      // Undeclared exception!
      try { 
        expressionParser0.parse();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Missing ')' after function arguments. (near position 4)
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("5!r", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
      // Undeclared exception!
      try { 
        expressionParser0.parse();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unexpected trailing input. (near position 2)
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("+4", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
      double double0 = expressionParser0.parse();
      assertEquals(4.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("02^2FE(Chm", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
      // Undeclared exception!
      try { 
        expressionParser0.parse();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unexpected trailing input. (near position 4)
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("0%2)EfVhQb", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
      // Undeclared exception!
      try { 
        expressionParser0.parse();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unexpected trailing input. (near position 3)
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("88*^!5uIJjztMgWde", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
      // Undeclared exception!
      try { 
        expressionParser0.parse();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Expected a number, variable, function call, or parenthesized expression. (near position 3)
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("QNdb(8-dBh", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
      // Undeclared exception!
      try { 
        expressionParser0.parse();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("5+fBtPBMMEbg+du7F2", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
      // Undeclared exception!
      try { 
        expressionParser0.parse();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("7/3<9TpeZ", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
      // Undeclared exception!
      try { 
        expressionParser0.parse();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unexpected trailing input. (near position 5)
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("7E3<9TpeZ", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
      // Undeclared exception!
      try { 
        expressionParser0.parse();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unexpected trailing input. (near position 5)
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("-7>3<KGKeZ", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
      // Undeclared exception!
      try { 
        expressionParser0.parse();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ExpressionParser expressionParser0 = new ExpressionParser("73>9TpeZ", (ExpressionParser.SymbolResolver) null, (ExpressionParser.FunctionResolver) null);
      // Undeclared exception!
      try { 
        expressionParser0.parse();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unexpected trailing input. (near position 4)
         //
         verifyException("com.example.calculator.ExpressionParser", e);
      }
  }
}
