/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 20 00:02:36 GMT 2026
 */

package com.example.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.calculator.FunctionDefinition;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FunctionDefinition_ESTest extends FunctionDefinition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FunctionDefinition functionDefinition0 = new FunctionDefinition("uJ", (-1), (-1), "*:eF&K#RG.$3to", (FunctionDefinition.FunctionImplementation) null);
      String string0 = functionDefinition0.name();
      assertEquals("uJ", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FunctionDefinition functionDefinition0 = new FunctionDefinition("", 0, 0, "", (FunctionDefinition.FunctionImplementation) null);
      String string0 = functionDefinition0.description();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FunctionDefinition functionDefinition0 = new FunctionDefinition("", 1, 1, "+]", (FunctionDefinition.FunctionImplementation) null);
      int int0 = functionDefinition0.minArgs();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FunctionDefinition functionDefinition0 = new FunctionDefinition("", 0, 0, "", (FunctionDefinition.FunctionImplementation) null);
      int int0 = functionDefinition0.maxArgs();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FunctionDefinition functionDefinition0 = new FunctionDefinition("0_r", 0, 1, "", (FunctionDefinition.FunctionImplementation) null);
      FunctionDefinition.FunctionImplementation functionDefinition_FunctionImplementation0 = functionDefinition0.implementation();
      assertNull(functionDefinition_FunctionImplementation0);
  }
}
