/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 19 23:53:16 GMT 2026
 */

package com.example.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.calculator.HistoryEntry;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HistoryEntry_ESTest extends HistoryEntry_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HistoryEntry historyEntry0 = new HistoryEntry((-1), "14f8n\"/$YC_P54*k1", "14f8n\"/$YC_P54*k1");
      String string0 = historyEntry0.output();
      assertEquals("14f8n\"/$YC_P54*k1", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HistoryEntry historyEntry0 = new HistoryEntry(0, "9T7MOb&={,Fv", (String) null);
      int int0 = historyEntry0.index();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HistoryEntry historyEntry0 = new HistoryEntry((-1), "14f8n\"/$YC_P54*k1", "14f8n\"/$YC_P54*k1");
      String string0 = historyEntry0.input();
      assertEquals("14f8n\"/$YC_P54*k1", string0);
  }
}
