/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 19 23:54:45 GMT 2026
 */

package com.example.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.calculator.NumberFormatUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NumberFormatUtil_ESTest extends NumberFormatUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = NumberFormatUtil.format((-1975.54194028));
      assertEquals("-1975.54194028", string0);
  }
}
