/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 20 00:03:07 GMT 2026
 */

package com.example.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.calculator.StatementSplitter;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class StatementSplitter_ESTest extends StatementSplitter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        StatementSplitter.split("u(vI;\"A!#Xqvd~r,I_");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unmatched '(' in expression.
         //
         verifyException("com.example.calculator.StatementSplitter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      List<String> list0 = StatementSplitter.split("u8r_&C:OZ|!X;");
      assertEquals(1, list0.size());
      assertFalse(list0.contains("u8r_&C:OZ|!X;"));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        StatementSplitter.split("*)sT0~\"63Um,,)");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unmatched ')' near position 1
         //
         verifyException("com.example.calculator.StatementSplitter", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      List<String> list0 = StatementSplitter.split("`IqP.(J1)engoHi$*[T");
      assertTrue(list0.contains("`IqP.(J1)engoHi$*[T"));
  }
}
